name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 檢出程式碼
      uses: actions/checkout@v5
      with:
        ref: ${{ github.sha }}
        submodules: 'recursive'
        fetch-depth: 0

    - name: 設定 Java
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'zulu'

    - name: 設定 Gradle
      uses: gradle/actions/setup-gradle@v5

    - name: 授予 gradlew 執行權限
      run: chmod +x gradlew

    - name: 使用 Gradle 測試並構建
      run: ./gradlew test build
